/// A token stores the user authentication token automatically generated by Twitter.
pub struct Token {
    /// Consumer API Key
    pub consumer_key: String,
    /// Consumer API Secret Key
    pub consumer_secret: String,
    /// Access Token
    pub access_token: String,
    /// Access Token Secret
    pub access_token_secret: String
}

impl Token {
    /// Create a new token, passing in your Twitter credentials.
    pub fn new(consumer_key: String, consumer_secret: String, access_token: String, access_token_secret: String) -> Self {
        Token {
            consumer_key,
            consumer_secret,
            access_token,
            access_token_secret
        }
    }
}
